# Generated by Django 3.2.16 on 2022-12-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='hotel',
        ),
    ]
